# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentop < Formula
  desc "htop for AI coding agents — find and reap idle Claude/cmux/emdash sessions"
  homepage "https://github.com/thesatellite-ai/agentop"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thesatellite-ai/agentop/releases/download/v0.1.2/agentop_darwin_amd64.tar.gz"
      sha256 "607b3909f48c76eea4ae27d9582a6e0d012ecb04d10a99ec83aebf7a567353cc"

      define_method(:install) do
        bin.install "agentop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thesatellite-ai/agentop/releases/download/v0.1.2/agentop_darwin_arm64.tar.gz"
      sha256 "f8cfbc53bc3add89c52c96ead69237b7100299a15bf04e3ae568ef7f2ebc801b"

      define_method(:install) do
        bin.install "agentop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/agentop/releases/download/v0.1.2/agentop_linux_amd64.tar.gz"
      sha256 "022988eeffc9f826193fc54ca9bf8faeec0e1ea1f28113326d96c22364e0a881"
      define_method(:install) do
        bin.install "agentop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/agentop/releases/download/v0.1.2/agentop_linux_arm64.tar.gz"
      sha256 "422a71be23a907adf04949c54ce123acb4ae50f1690a6a8d30b6249a150c989e"
      define_method(:install) do
        bin.install "agentop"
      end
    end
  end

  test do
    system "#{bin}/agentop", "version"
  end
end
