# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Local-first knowledge & context store for AI coding agents"
  homepage "https://github.com/thesatellite-ai/lore"
  version "0.1.0"
  license "PolyForm-Perimeter-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.0/lore_darwin_amd64.tar.gz"
      sha256 "034465dffcfa3a3aa0dfcc2670fbdfcd2abc82867d7dde72b860efab81df341a"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.0/lore_darwin_arm64.tar.gz"
      sha256 "b33525e79240241be3abb7b8fc2feb03f401426bb102a493d8c7d057d94237b0"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.0/lore_linux_amd64.tar.gz"
      sha256 "6f2c3267c3c2c28e4543f87168a1a9ab9d3aac846971fb6691b56840ee0e3cb5"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.0/lore_linux_arm64.tar.gz"
      sha256 "64e73db62022fea85be63b10dce781fde805c4c66ad175e6050214f7b93f1859"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "version"
  end
end
