# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Local-first knowledge & context store for AI coding agents"
  homepage "https://github.com/thesatellite-ai/lore"
  version "0.1.8"
  license "PolyForm-Perimeter-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.8/lore_darwin_amd64.tar.gz"
      sha256 "ac73fbe7dbeee0b79f5a5052d20360fce640ecde4dc0ac3ec6348ad81546212a"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.8/lore_darwin_arm64.tar.gz"
      sha256 "07afa90aa450206fb609021583fc9a4ae070454a7cd0d8fd0bc3a2f303a2ac3d"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.8/lore_linux_amd64.tar.gz"
      sha256 "eb9990c65c285708fd86cd8d3a3d00d4b97e1aeee589850ed226df6925027b59"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.8/lore_linux_arm64.tar.gz"
      sha256 "7c1f97d0fdc591ac2777818245439570ac3569ee2f10a74930955e26c93da0a2"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "version"
  end
end
