# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lore < Formula
  desc "Local-first knowledge & context store for AI coding agents"
  homepage "https://github.com/thesatellite-ai/lore"
  version "0.1.3"
  license "PolyForm-Perimeter-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.3/lore_darwin_amd64.tar.gz"
      sha256 "0a0eae9f151166b6f7f03fe360f0df8576e4c343aa6a5e8022765a33d1a4e438"

      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.3/lore_darwin_arm64.tar.gz"
      sha256 "b3792cc395bc874ea510dd1c81c8b24acf36da5d56f190e676a3aed5d35e71fa"

      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.3/lore_linux_amd64.tar.gz"
      sha256 "8ec6ead3680b7e7d5b3b112e9995d430c18e3ea9acc7bdccda5797ab8542daab"
      define_method(:install) do
        bin.install "lore"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thesatellite-ai/lore/releases/download/v0.1.3/lore_linux_arm64.tar.gz"
      sha256 "81829f8b1c9dcb47da65991115b6ae83def7ba6767032d9cab7f48ba6fe9659b"
      define_method(:install) do
        bin.install "lore"
      end
    end
  end

  test do
    system "#{bin}/lore", "version"
  end
end
